### ISSUE TITLE
Dwarf parser interface

### ISSUE THREAD

**Issue by sdmaclea** [southpolenator/SharpDebug#41]
I was looking for a managed Dwarf parser.  I saw comments in ElfSharp about your dwarf parser. I took a quick look at the code it seemed pretty clean so I decided to kick the tires. I tried to use the as a standalone ELF Dwarf Symbol parser.

Summary of my findings:

* The SharpDebug.DwarfSymbolProvider public constructor is not currently usable because the `SharpDebug.Engine.Module` constructor is `internal`.
* konrad-kruczynski/elfsharp#49
* There was an issue with NormalizeAddress finding the correct sections.
* There were a lots of exceptions being thrown from unimplemented location decode functionality
* There were lots of issues around decoding extra names.
* The parser was very slow. The libcoreclr.so.dbg dwarf info is very large and parsing takes considerable time. For my purposes I only need a small subset of the dwarf symbols so converting them all to C# is unnecessary.  I need a more on demand parser.
* The typeId generated do not correlate to the debug info offset.  I found this strange as it reduced traceability. It also forced a full decode of the info.

If you are interested my branch is here https://github.com/sdmaclea/SharpDebug/tree/DwarfSymbolProvider. With those changes and the change to ElfSharp I was able to fully parse the dwarf symbols from `libcoreclr.so.dbg` (see ElfSharp issue above for relevant instructions).

**Comment by southpolenator** [comment]
Thanks for looking into issues. I've started work on separating Dwarf parser out of this project into SharpDrawf project that would be standalone. Similar path happened to SharpPdb.
Please do send PR with your changes and I'll be more than happy to provide feedback and take the changes :) Later I'll move them to new project when it is ready...
